package exception.throw_;

public class ThrowEX01 {
	public static void main(String[] args) {
		try {
			System.out.println("결과 : " + calc(10));
			System.out.println("결과 : " + calc(-10));
		} catch (Exception e) {
			System.out.println("반드시 양수값을 전달해야 합니다.");
		}

	} // main end

	public static int calc(int n) throws Exception {
		if (n < 0) {
			throw new Exception(); // 예외 생성
		}
		int sum = 0;
		for (int i = 1; i <= n; i++) {
			sum += i;
		}
		return sum;
	} // calc end

}
