package exception.throws_;

public class MainClass {
	public static void main(String[] args) { // main에서 throws하면 JVM에게 넘어감.
		try {
			new ThrowsEx02();
		} catch (Exception e) {
			System.out.println("예외발생");
		}

		/*
		 * bbb메서드를 try-catch로 처리시 메서드 끝까지 처리
		 * 생성자 호출
		 * aaa호출
		 * bbb호출
		 * bbb종료
		 * aaa종료
		 * 생성자 종료
		 */
		
		/*
		 * throws로 넘길시
		 * 생성자 호출
aaa호출
bbb호출
예외발생

		 */
		
	}
}
